- hosts: localhost
  vars:
    node_ver: "16.15.0"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/slack-setup.yml
    - include: tasks/brave-setup.yml
    - include: tasks/tools-setup.yml
    - include: tasks/python-env.yml
    - include: tasks/dbeaver-setup.yml