- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - core

- name: Install System Packages 2 (unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - core

- name: Install System Packages 3 (pyenv)
  become: true
  apt:
    name: ["libssl-dev", "zlib1g-dev", "libbz2-dev", "libreadline-dev", "libsqlite3-dev", "llvm", "libncursesw5-dev", "xz-utils", "tk-dev", "libxml2-dev", "libxmlsec1-dev", "libffi-dev", "liblzma-dev"]
  tags:
    - install
    - core

- name: Install System Packages 4 (the rest)
  become: true
  apt:
    name: ["wget", "curl", "htop", "golang", "lsof"]
  tags:
    - install
    - core
