- name: Setup Node
  become: yes
  become_flags: -i
  become_user: denzel
  tags:
    - install
    - node
  block:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh
        create: yes

    - name: Install node
      shell: |
        source {{ ansible_env.HOME }}/.nvm/nvm.sh
        nvm install {{node_ver}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{node_ver}}" 
